#ifndef CAIRO_LIB_H
#define CAIRO_LIB_H

#include "cairo.h"

typedef struct _cairo_lib {
cairo_t* (*create)(cairo_surface_t *target);
cairo_t* (*reference) (cairo_t *cr);
void (*destroy) (cairo_t *cr);
unsigned int (*get_reference_count) (cairo_t *cr);
void* (*get_user_data) (cairo_t *cr, const cairo_user_data_key_t *key);
cairo_status_t (*set_user_data) (cairo_t *cr, const cairo_user_data_key_t *key, void *user_data, cairo_destroy_func_t destroy);
void (*save) (cairo_t *cr);
void (*restore) (cairo_t *cr);
void (*push_group) (cairo_t *cr);
void (*push_group_with_content) (cairo_t *cr, cairo_content_t content);
cairo_pattern_t* (*pop_group) (cairo_t *cr);
void (*pop_group_to_source) (cairo_t *cr);
void (*set_operator) (cairo_t *cr, cairo_operator_t op);
void (*set_source) (cairo_t *cr, cairo_pattern_t *source);
void (*set_source_rgb) (cairo_t *cr, double red, double green, double blue);
void (*set_source_rgba) (cairo_t *cr, double red, double green, double blue, double alpha);
void (*set_source_surface) (cairo_t *cr, cairo_surface_t *surface, double x, double y);
void (*set_tolerance) (cairo_t *cr, double tolerance);
void (*set_antialias) (cairo_t *cr, cairo_antialias_t antialias);
void (*set_line_cap) (cairo_t *cr, cairo_line_cap_t line_cap); 
void (*set_line_join) (cairo_t *cr, cairo_line_join_t line_join); 
void (*set_dash) (cairo_t *cr, const double *dashes, int num_dashes, double offset);
void (*set_miter_limit) (cairo_t *cr, double limit);
void (*translate) (cairo_t *cr, double tx, double ty);
void (*scale) (cairo_t *cr, double sx, double sy);
void (*rotate) (cairo_t *cr, double angle);
void (*transform) (cairo_t *cr, const cairo_matrix_t *matrix);
void (*set_matrix) (cairo_t *cr, const cairo_matrix_t *matrix);
void (*identity_matrix) (cairo_t *cr);
void (*user_to_device) (cairo_t *cr, double *x, double *y);
void (*user_to_device_distance) (cairo_t *cr, double *dx, double *dy);
void (*device_to_user) (cairo_t *cr, double *x, double *y);
void (*device_to_user_distance) (cairo_t *cr, double *dx, double *dy);
void (*new_path) (cairo_t *cr);
void (*move_to) (cairo_t *cr, double x, double y);
void (*new_sub_path) (cairo_t *cr);
void (*line_to) (cairo_t *cr, double x, double y);
void (*curve_to) (cairo_t *cr, double x1, double y1, double x2, double y2, double x3, double y3);
void (*arc) (cairo_t *cr, double xc, double yc, double radius, double angle1, double angle2);
void (*arc_negative) (cairo_t *cr, double xc, double yc, double radius, double angle1, double angle2);
void (*rel_move_to) (cairo_t *cr, double dx, double dy);
void (*rel_line_to) (cairo_t *cr, double dx, double dy);
void (*rel_curve_to) (cairo_t *cr, double dx1, double dy1, double dx2, double dy2, double dx3, double dy3);
void (*rectangle) (cairo_t *cr, double x, double y, double width, double height);
void (*close_path) (cairo_t *cr);
void (*paint) (cairo_t *cr);
void (*paint_with_alpha) (cairo_t *cr, double alpha);
void (*mask) (cairo_t *cr, cairo_pattern_t *pattern);
void (*mask_surface) (cairo_t *cr, cairo_surface_t *surface, double surface_x, double surface_y);
void (*stroke) (cairo_t *cr);
void (*stroke_preserve) (cairo_t *cr);
void (*fill) (cairo_t *cr);
void (*fill_preserve) (cairo_t *cr);
void (*copy_page) (cairo_t *cr);
void (*show_page) (cairo_t *cr);
cairo_bool_t (*in_stroke) (cairo_t *cr, double x, double y);
cairo_bool_t (*in_fill) (cairo_t *cr, double x, double y);
void (*stroke_extents) (cairo_t *cr, double *x1, double *y1, double *x2, double *y2);
void (*fill_extents) (cairo_t *cr, double *x1, double *y1, double *x2, double *y2);
void (*reset_clip) (cairo_t *cr);
void (*clip) (cairo_t *cr);
void (*clip_preserve) (cairo_t *cr);
void (*clip_extents) (cairo_t *cr, double *x1, double *y1, double *x2, double *y2);
cairo_rectangle_list_t* (*copy_clip_rectangle_list) (cairo_t *cr);
void (*rectangle_list_destroy) (cairo_rectangle_list_t *rectangle_list);
cairo_font_options_t* (*font_options_create) (void);
cairo_font_options_t* (*font_options_copy) (const cairo_font_options_t *original);
void (*font_options_destroy) (cairo_font_options_t *options);
cairo_status_t (*font_options_status) (cairo_font_options_t *options);
void (*font_options_merge) (cairo_font_options_t *options, const cairo_font_options_t *other);
cairo_bool_t (*font_options_equal) (const cairo_font_options_t *options, const cairo_font_options_t *other);
unsigned long (*font_options_hash) (const cairo_font_options_t *options);
void (*font_options_set_antialias) (cairo_font_options_t *options, cairo_antialias_t antialias);
cairo_antialias_t (*font_options_get_antialias) (const cairo_font_options_t *options);
void (*font_options_set_subpixel_order) (cairo_font_options_t *options, cairo_subpixel_order_t subpixel_order);
cairo_subpixel_order_t (*font_options_get_subpixel_order) (const cairo_font_options_t *options);
void (*font_options_set_hint_style) (cairo_font_options_t *options, cairo_hint_style_t hint_style);
cairo_hint_style_t (*font_options_get_hint_style) (const cairo_font_options_t *options);
void (*font_options_set_hint_metrics) (cairo_font_options_t *options, cairo_hint_metrics_t hint_metrics);
cairo_hint_metrics_t (*font_options_get_hint_metrics) (const cairo_font_options_t *options);
void (*select_font_face) (cairo_t *cr, const char *family, cairo_font_slant_t slant, cairo_font_weight_t weight);
void (*set_font_size) (cairo_t *cr, double size);
void (*set_font_matrix) (cairo_t *cr, const cairo_matrix_t *matrix);
void (*get_font_matrix) (cairo_t *cr, cairo_matrix_t *matrix);
void (*set_font_options) (cairo_t *cr, const cairo_font_options_t *options);
void (*get_font_options) (cairo_t *cr, cairo_font_options_t *options);
void (*set_font_face) (cairo_t *cr, cairo_font_face_t *font_face);
cairo_font_face_t* (*get_font_face) (cairo_t *cr);
void (*set_scaled_font) (cairo_t *cr, const cairo_scaled_font_t *scaled_font);
cairo_scaled_font_t* (*get_scaled_font) (cairo_t *cr);
void (*show_text) (cairo_t *cr, const char *utf8);
void (*show_glyphs) (cairo_t *cr, const cairo_glyph_t *glyphs, int num_glyphs);
void (*text_path) (cairo_t *cr, const char *utf8);
void (*glyph_path) (cairo_t *cr, const cairo_glyph_t *glyphs, int num_glyphs);
void (*text_extents) (cairo_t *cr, const char *utf8, cairo_text_extents_t *extents);
void (*glyph_extents) (cairo_t *cr, const cairo_glyph_t *glyphs, int num_glyphs, cairo_text_extents_t *extents);
void (*font_extents) (cairo_t *cr, cairo_font_extents_t *extents);
cairo_font_face_t* (*font_face_reference) (cairo_font_face_t *font_face);
void (*font_face_destroy) (cairo_font_face_t *font_face);
unsigned int (*font_face_get_reference_count) (cairo_font_face_t *font_face);
cairo_status_t (*font_face_status) (cairo_font_face_t *font_face);
cairo_font_type_t (*font_face_get_type) (cairo_font_face_t *font_face);
void* (*font_face_get_user_data) (cairo_font_face_t *font_face, const cairo_user_data_key_t *key);
cairo_status_t (*font_face_set_user_data) (cairo_font_face_t *font_face, const cairo_user_data_key_t *key, void *user_data, cairo_destroy_func_t destroy);
cairo_scaled_font_t* (*scaled_font_create) (cairo_font_face_t *font_face, const cairo_matrix_t *font_matrix, const cairo_matrix_t *ctm, const cairo_font_options_t *options);
cairo_scaled_font_t* (*scaled_font_reference) (cairo_scaled_font_t *scaled_font);
void (*scaled_font_destroy) (cairo_scaled_font_t *scaled_font);
unsigned int (*scaled_font_get_reference_count) (cairo_scaled_font_t *scaled_font);
cairo_status_t (*scaled_font_status) (cairo_scaled_font_t *scaled_font);
cairo_font_type_t (*scaled_font_get_type) (cairo_scaled_font_t *scaled_font);
void* (*scaled_font_get_user_data) (cairo_scaled_font_t *scaled_font, const cairo_user_data_key_t *key);
cairo_status_t (*scaled_font_set_user_data) (cairo_scaled_font_t *scaled_font, const cairo_user_data_key_t *key, void *user_data, cairo_destroy_func_t destroy);
void (*scaled_font_extents) (cairo_scaled_font_t *scaled_font, cairo_font_extents_t *extents);
void (*scaled_font_text_extents) (cairo_scaled_font_t *scaled_font, const char *utf8, cairo_text_extents_t *extents); 
void (*scaled_font_glyph_extents) (cairo_scaled_font_t *scaled_font, const cairo_glyph_t *glyphs, int num_glyphs, cairo_text_extents_t *extents);
cairo_font_face_t* (*scaled_font_get_font_face) (cairo_scaled_font_t *scaled_font);
void (*scaled_font_get_font_matrix) (cairo_scaled_font_t *scaled_font, cairo_matrix_t *font_matrix);
void (*scaled_font_get_ctm) (cairo_scaled_font_t *scaled_font, cairo_matrix_t *ctm);
void (*scaled_font_get_font_options) (cairo_scaled_font_t *scaled_font, cairo_font_options_t *options);
cairo_operator_t (*get_operator) (cairo_t *cr);
cairo_pattern_t* (*get_source) (cairo_t *cr);
double (*get_tolerance) (cairo_t *cr);
cairo_antialias_t (*get_antialias) (cairo_t *cr);
void (*get_current_point) (cairo_t *cr, double *x, double *y);
cairo_fill_rule_t (*get_fill_rule) (cairo_t *cr);
double (*get_line_width) (cairo_t *cr);
cairo_line_cap_t (*get_line_cap) (cairo_t *cr);
cairo_line_join_t (*get_line_join) (cairo_t *cr);
double (*get_miter_limit) (cairo_t *cr);
int (*get_dash_count) (cairo_t *cr);
void (*get_dash) (cairo_t *cr, double *dashes, double *offset);
void (*get_matrix) (cairo_t *cr, cairo_matrix_t *matrix);
cairo_surface_t* (*get_target) (cairo_t *cr);
cairo_surface_t* (*get_group_target) (cairo_t *cr);
cairo_path_t* (*copy_path) (cairo_t *cr);
cairo_path_t* (*copy_path_flat) (cairo_t *cr);
void (*append_path) (cairo_t *cr, const cairo_path_t *path);
void (*path_destroy) (cairo_path_t *path);
cairo_status_t (*status) (cairo_t *cr);
const char* (*status_to_string) (cairo_status_t status);
cairo_surface_t* (*surface_create_similar) (cairo_surface_t *other, cairo_content_t content, int width, int height);
cairo_surface_t* (*surface_reference) (cairo_surface_t *surface);
void (*surface_finish) (cairo_surface_t *surface);
void (*surface_destroy) (cairo_surface_t *surface);
unsigned int (*surface_get_reference_count) (cairo_surface_t *surface);
cairo_status_t (*surface_status) (cairo_surface_t *surface);
cairo_surface_type_t (*surface_get_type) (cairo_surface_t *surface);
cairo_content_t (*surface_get_content) (cairo_surface_t *surface);
void* (*surface_get_user_data) (cairo_surface_t *surface, const cairo_user_data_key_t *key);
cairo_status_t (*surface_set_user_data) (cairo_surface_t *surface, const cairo_user_data_key_t *key, void *user_data, cairo_destroy_func_t destroy);
void (*surface_get_font_options) (cairo_surface_t *surface, cairo_font_options_t *options);
void (*surface_flush) (cairo_surface_t *surface);
void (*surface_mark_dirty) (cairo_surface_t *surface);
void (*surface_mark_dirty_rectangle) (cairo_surface_t *surface, int x, int y, int width, int height);
void (*surface_set_device_offset) (cairo_surface_t *surface, double x_offset, double y_offset);
void (*surface_get_device_offset) (cairo_surface_t *surface, double *x_offset, double *y_offset);
void (*surface_set_fallback_resolution) (cairo_surface_t *surface, double x_pixels_per_inch, double y_pixels_per_inch);
cairo_surface_t* (*image_surface_create) (cairo_format_t format, int width, int height);
cairo_surface_t* (*image_surface_create_for_data) (unsigned char *data, cairo_format_t format, int width, int height, int stride);
unsigned char* (*image_surface_get_data) (cairo_surface_t *surface);
cairo_format_t (*image_surface_get_format) (cairo_surface_t *surface);
int (*image_surface_get_width) (cairo_surface_t *surface);
int (*image_surface_get_height) (cairo_surface_t *surface);
int (*image_surface_get_stride) (cairo_surface_t *surface);
cairo_pattern_t* (*pattern_create_rgb) (double red, double green, double blue);
cairo_pattern_t* (*pattern_create_rgba) (double red, double green, double blue, double alpha); 
cairo_pattern_t* (*pattern_create_for_surface) (cairo_surface_t *surface);
cairo_pattern_t* (*pattern_create_linear) (double x0, double y0, double x1, double y1); 
cairo_pattern_t* (*pattern_create_radial) (double cx0, double cy0, double radius0, double cx1, double cy1, double radius1); 
cairo_pattern_t* (*pattern_reference) (cairo_pattern_t *pattern);
void (*pattern_destroy) (cairo_pattern_t *pattern);
unsigned int (*pattern_get_reference_count) (cairo_pattern_t *pattern);
cairo_status_t (*pattern_status) (cairo_pattern_t *pattern);
void* (*pattern_get_user_data) (cairo_pattern_t *pattern, const cairo_user_data_key_t *key); 
cairo_status_t (*pattern_set_user_data) (cairo_pattern_t *pattern, const cairo_user_data_key_t *key, void *user_data, cairo_destroy_func_t destroy);
cairo_pattern_type_t (*pattern_get_type) (cairo_pattern_t *pattern);
void (*pattern_add_color_stop_rgb) (cairo_pattern_t *pattern, double offset, double red, double green, double blue);
void (*pattern_add_color_stop_rgba) (cairo_pattern_t *pattern, double offset, double red, double green, double blue, double alpha);
void (*pattern_set_matrix) (cairo_pattern_t *pattern, const cairo_matrix_t *matrix);
void (*pattern_get_matrix) (cairo_pattern_t *pattern, cairo_matrix_t *matrix);
void (*pattern_set_extend) (cairo_pattern_t *pattern, cairo_extend_t extend);
cairo_extend_t (*pattern_get_extend) (cairo_pattern_t *pattern);
void (*pattern_set_filter) (cairo_pattern_t *pattern, cairo_filter_t filter);
cairo_filter_t (*pattern_get_filter) (cairo_pattern_t *pattern);
cairo_status_t (*pattern_get_rgba) (cairo_pattern_t *pattern, double *red, double *green, double *blue, double *alpha);
cairo_status_t (*pattern_get_surface) (cairo_pattern_t *pattern, cairo_surface_t **surface);
cairo_status_t (*pattern_get_color_stop_rgba) (cairo_pattern_t *pattern, int index, double *offset, double *red, double *green, double *blue, double *alpha);
cairo_status_t (*pattern_get_color_stop_count) (cairo_pattern_t *pattern, int *count);
cairo_status_t (*pattern_get_linear_points) (cairo_pattern_t *pattern, double *x0, double *y0, double *x1, double *y1);
cairo_status_t (*pattern_get_radial_circles) (cairo_pattern_t *pattern, double *x0, double *y0, double *r0, double *x1, double *y1, double *r1);
void (*matrix_init) (cairo_matrix_t *matrix, double xx, double yx, double xy, double yy, double x0, double y0);
void (*matrix_init_identity) (cairo_matrix_t *matrix);
void (*matrix_init_translate) (cairo_matrix_t *matrix, double tx, double ty);
void (*matrix_init_scale) (cairo_matrix_t *matrix, double sx, double sy);
void (*matrix_init_rotate) (cairo_matrix_t *matrix, double radians);
void (*matrix_translate) (cairo_matrix_t *matrix, double tx, double ty);
void (*matrix_scale) (cairo_matrix_t *matrix, double sx, double sy);
void (*matrix_rotate) (cairo_matrix_t *matrix, double radians);
cairo_status_t (*matrix_invert) (cairo_matrix_t *matrix);
void (*matrix_multiply) (cairo_matrix_t *result, const cairo_matrix_t *a, const cairo_matrix_t *b);
void (*matrix_transform_distance) (const cairo_matrix_t *matrix, double *dx, double *dy); 
void (*matrix_transform_point) (const cairo_matrix_t *matrix, double *x, double *y);
void (*debug_reset_static_data) (void);
void (*set_line_width) (cairo_t *cr, double width);
void (*surface_write_to_png) (cairo_surface_t *surface, const char *filename);
cairo_status_t (*surface_write_to_png_stream) (cairo_surface_t *surface, cairo_write_func_t write_func, void *closure);
cairo_surface_t* (*image_surface_create_from_png) (const char *filename);
cairo_surface_t* (*image_surface_create_from_png_stream) (cairo_read_func_t read_func, void *closure);

} CAIROlib;

#if _WINDOWS
cairo_public int _cairo_lib (CAIROlib *lib);
#endif

#if __APPLE__
#pragma warning disable 556

void * getDLLEntry( void *pLib, const char * entryName)
{
	void * temp = dlsym(pLib, entryName);
	char * error;
	
	if(temp == NULL) {
		if(error=dlerror()) {
			fprintf(stderr, "%s: not found error:%s\n",entryName, error);
		} else {
			fprintf(stderr, "%s: not found in dlyb\n", entryName);
		}
	}
	return temp;
}

int cairoLib(CAIROlib *lib, void *pLib)
{
	if(lib && pLib) {
		memset( lib, 0, sizeof(CAIROlib));
		if( !(lib->create =							getDLLEntry(pLib, "cairo_create"))) return 0;
		if( !(lib->reference =						getDLLEntry(pLib, "cairo_reference"))) return 0;
		if( !(lib->destroy =						getDLLEntry(pLib, "cairo_destroy"))) return 0;
		if( !(lib->get_reference_count =			getDLLEntry(pLib, "cairo_get_reference_count"))) return 0;
		if( !(lib->get_user_data =					getDLLEntry(pLib, "cairo_get_user_data"))) return 0;
		if( !(lib->set_user_data =					getDLLEntry(pLib, "cairo_set_user_data"))) return 0;
		if( !(lib->save =							getDLLEntry(pLib, "cairo_save"))) return 0;
		if( !(lib->restore =						getDLLEntry(pLib, "cairo_restore"))) return 0;
		if( !(lib->push_group =						getDLLEntry(pLib, "cairo_push_group"))) return 0;
		if( !(lib->push_group_with_content =		getDLLEntry(pLib, "cairo_push_group_with_content"))) return 0;
		if( !(lib->pop_group =						getDLLEntry(pLib, "cairo_pop_group"))) return 0;
		if( !(lib->pop_group_to_source =			getDLLEntry(pLib, "cairo_pop_group_to_source"))) return 0;
		if( !(lib->set_operator =					getDLLEntry(pLib, "cairo_set_operator"))) return 0;
		if( !(lib->set_source =						getDLLEntry(pLib, "cairo_set_source"))) return 0;
		if( !(lib->set_source_rgb =					getDLLEntry(pLib, "cairo_set_source_rgb"))) return 0;
		if( !(lib->set_source_rgba =				getDLLEntry(pLib, "cairo_set_source_rgba"))) return 0;
		if( !(lib->set_source_surface =				getDLLEntry(pLib, "cairo_set_source_surface"))) return 0;
		if( !(lib->set_tolerance =					getDLLEntry(pLib, "cairo_set_tolerance"))) return 0;
		if( !(lib->set_antialias =					getDLLEntry(pLib, "cairo_set_antialias"))) return 0;
		if( !(lib->set_line_cap =					getDLLEntry(pLib, "cairo_set_line_cap"))) return 0;
		if( !(lib->set_line_join =					getDLLEntry(pLib, "cairo_set_line_join"))) return 0;
		if( !(lib->set_dash =						getDLLEntry(pLib, "cairo_set_dash"))) return 0;
		if( !(lib->set_miter_limit =				getDLLEntry(pLib, "cairo_set_miter_limit"))) return 0;
		if( !(lib->translate =						getDLLEntry(pLib, "cairo_translate"))) return 0;
		if( !(lib->scale =							getDLLEntry(pLib, "cairo_scale"))) return 0;
		if( !(lib->rotate =							getDLLEntry(pLib, "cairo_rotate"))) return 0;
		if( !(lib->transform =						getDLLEntry(pLib, "cairo_transform"))) return 0;
		if( !(lib->set_matrix =						getDLLEntry(pLib, "cairo_set_matrix"))) return 0;
		if( !(lib->identity_matrix =				getDLLEntry(pLib, "cairo_identity_matrix"))) return 0;
		if( !(lib->user_to_device =					getDLLEntry(pLib, "cairo_user_to_device"))) return 0;
		if( !(lib->user_to_device_distance =		getDLLEntry(pLib, "cairo_user_to_device_distance"))) return 0;
		if( !(lib->device_to_user =					getDLLEntry(pLib, "cairo_device_to_user"))) return 0;
		if( !(lib->device_to_user_distance =		getDLLEntry(pLib, "cairo_device_to_user_distance"))) return 0;
		if( !(lib->new_path =						getDLLEntry(pLib, "cairo_new_path"))) return 0;
		if( !(lib->move_to =						getDLLEntry(pLib, "cairo_move_to"))) return 0;
		if( !(lib->new_sub_path =					getDLLEntry(pLib, "cairo_new_sub_path"))) return 0;
		if( !(lib->line_to =						getDLLEntry(pLib, "cairo_line_to"))) return 0;
		if( !(lib->curve_to =						getDLLEntry(pLib, "cairo_curve_to"))) return 0;
		if( !(lib->arc =							getDLLEntry(pLib, "cairo_arc"))) return 0;
		if( !(lib->arc_negative =					getDLLEntry(pLib, "cairo_arc_negative"))) return 0;
		if( !(lib->rel_move_to =					getDLLEntry(pLib, "cairo_rel_move_to"))) return 0;
		if( !(lib->rel_line_to =					getDLLEntry(pLib, "cairo_rel_line_to"))) return 0;
		if( !(lib->rel_curve_to =					getDLLEntry(pLib, "cairo_rel_curve_to"))) return 0;
		if( !(lib->rectangle =						getDLLEntry(pLib, "cairo_rectangle"))) return 0;
		if( !(lib->close_path =						getDLLEntry(pLib, "cairo_close_path"))) return 0;
		if( !(lib->paint =							getDLLEntry(pLib, "cairo_paint"))) return 0;
		if( !(lib->paint_with_alpha =				getDLLEntry(pLib, "cairo_paint_with_alpha"))) return 0;
		if( !(lib->mask =							getDLLEntry(pLib, "cairo_mask"))) return 0;
		if( !(lib->mask_surface =					getDLLEntry(pLib, "cairo_mask_surface"))) return 0;
		if( !(lib->stroke =							getDLLEntry(pLib, "cairo_stroke"))) return 0;
		if( !(lib->stroke_preserve =				getDLLEntry(pLib, "cairo_stroke_preserve"))) return 0;
		if( !(lib->fill =							getDLLEntry(pLib, "cairo_fill"))) return 0;
		if( !(lib->fill_preserve =					getDLLEntry(pLib, "cairo_fill_preserve"))) return 0;
		if( !(lib->copy_page =						getDLLEntry(pLib, "cairo_copy_page"))) return 0;
		if( !(lib->show_page =						getDLLEntry(pLib, "cairo_show_page"))) return 0;
		if( !(lib->in_stroke =						getDLLEntry(pLib, "cairo_in_stroke"))) return 0;
		if( !(lib->in_fill =						getDLLEntry(pLib, "cairo_in_fill"))) return 0;
		if( !(lib->stroke_extents =					getDLLEntry(pLib, "cairo_stroke_extents"))) return 0;
		if( !(lib->fill_extents =					getDLLEntry(pLib, "cairo_fill_extents"))) return 0;
		if( !(lib->reset_clip =						getDLLEntry(pLib, "cairo_reset_clip"))) return 0;
		if( !(lib->clip =							getDLLEntry(pLib, "cairo_clip"))) return 0;
		if( !(lib->clip_preserve =					getDLLEntry(pLib, "cairo_clip_preserve"))) return 0;
		if( !(lib->clip_extents =					getDLLEntry(pLib, "cairo_clip_extents"))) return 0;
		if( !(lib->copy_clip_rectangle_list =		getDLLEntry(pLib, "cairo_copy_clip_rectangle_list"))) return 0;
		if( !(lib->rectangle_list_destroy =			getDLLEntry(pLib, "cairo_rectangle_list_destroy"))) return 0;
		if( !(lib->font_options_create =			getDLLEntry(pLib, "cairo_font_options_create"))) return 0;
		if( !(lib->font_options_copy =				getDLLEntry(pLib, "cairo_font_options_copy"))) return 0;
		if( !(lib->font_options_destroy =			getDLLEntry(pLib, "cairo_font_options_destroy"))) return 0;
		if( !(lib->font_options_status =			getDLLEntry(pLib, "cairo_font_options_status"))) return 0;
		if( !(lib->font_options_merge =				getDLLEntry(pLib, "cairo_font_options_merge"))) return 0;
		if( !(lib->font_options_equal =				getDLLEntry(pLib, "cairo_font_options_equal"))) return 0;
		if( !(lib->font_options_hash =				getDLLEntry(pLib, "cairo_font_options_hash"))) return 0;
		if( !(lib->font_options_set_antialias =		getDLLEntry(pLib, "cairo_font_options_set_antialias"))) return 0;
		if( !(lib->font_options_get_antialias =		getDLLEntry(pLib, "cairo_font_options_get_antialias"))) return 0;
		if( !(lib->font_options_set_subpixel_order =getDLLEntry(pLib, "cairo_font_options_set_subpixel_order"))) return 0;
		if( !(lib->font_options_get_subpixel_order =getDLLEntry(pLib, "cairo_font_options_get_subpixel_order"))) return 0;
		if( !(lib->font_options_set_hint_style =	getDLLEntry(pLib, "cairo_font_options_set_hint_style"))) return 0;
		if( !(lib->font_options_get_hint_style =	getDLLEntry(pLib, "cairo_font_options_get_hint_style"))) return 0;
		if( !(lib->font_options_set_hint_metrics =	getDLLEntry(pLib, "cairo_font_options_set_hint_metrics"))) return 0;
		if( !(lib->font_options_get_hint_metrics =	getDLLEntry(pLib, "cairo_font_options_get_hint_metrics"))) return 0;
		if( !(lib->select_font_face =				getDLLEntry(pLib, "cairo_select_font_face"))) return 0;
		if( !(lib->set_font_size =					getDLLEntry(pLib, "cairo_set_font_size"))) return 0;
		if( !(lib->set_font_matrix =				getDLLEntry(pLib, "cairo_set_font_matrix"))) return 0;
		if( !(lib->get_font_matrix =				getDLLEntry(pLib, "cairo_get_font_matrix"))) return 0;
		if( !(lib->set_font_options =				getDLLEntry(pLib, "cairo_set_font_options"))) return 0;
		if( !(lib->get_font_options =				getDLLEntry(pLib, "cairo_get_font_options"))) return 0;
		if( !(lib->set_font_face =					getDLLEntry(pLib, "cairo_set_font_face"))) return 0;
		if( !(lib->get_font_face =					getDLLEntry(pLib, "cairo_get_font_face"))) return 0;
		if( !(lib->set_scaled_font =				getDLLEntry(pLib, "cairo_set_scaled_font"))) return 0;
		if( !(lib->get_scaled_font =				getDLLEntry(pLib, "cairo_get_scaled_font"))) return 0;
		if( !(lib->show_text =						getDLLEntry(pLib, "cairo_show_text"))) return 0;
		if( !(lib->show_glyphs =					getDLLEntry(pLib, "cairo_show_glyphs"))) return 0;
		if( !(lib->text_path =						getDLLEntry(pLib, "cairo_text_path"))) return 0;
		if( !(lib->glyph_path =						getDLLEntry(pLib, "cairo_glyph_path"))) return 0;
		if( !(lib->text_extents =					getDLLEntry(pLib, "cairo_text_extents"))) return 0;
		if( !(lib->glyph_extents =					getDLLEntry(pLib, "cairo_glyph_extents"))) return 0;
		if( !(lib->font_extents =					getDLLEntry(pLib, "cairo_font_extents"))) return 0;
		if( !(lib->font_face_reference =			getDLLEntry(pLib, "cairo_font_face_reference"))) return 0;
		if( !(lib->font_face_destroy =				getDLLEntry(pLib, "cairo_font_face_destroy"))) return 0;
		if( !(lib->font_face_get_reference_count =	getDLLEntry(pLib, "cairo_font_face_get_reference_count"))) return 0;
		if( !(lib->font_face_status =				getDLLEntry(pLib, "cairo_font_face_status"))) return 0;
		if( !(lib->font_face_get_type =				getDLLEntry(pLib, "cairo_font_face_get_type"))) return 0;
		if( !(lib->font_face_get_user_data =		getDLLEntry(pLib, "cairo_font_face_get_user_data"))) return 0;
		if( !(lib->font_face_set_user_data =		getDLLEntry(pLib, "cairo_font_face_set_user_data"))) return 0;
		if( !(lib->scaled_font_create =				getDLLEntry(pLib, "cairo_scaled_font_create"))) return 0;
		if( !(lib->scaled_font_reference =			getDLLEntry(pLib, "cairo_scaled_font_reference"))) return 0;
		if( !(lib->scaled_font_get_reference_count =getDLLEntry(pLib, "cairo_scaled_font_get_reference_count"))) return 0;
		if( !(lib->scaled_font_status =				getDLLEntry(pLib, "cairo_scaled_font_status"))) return 0;
		if( !(lib->scaled_font_get_type =			getDLLEntry(pLib, "cairo_scaled_font_get_type"))) return 0;
		if( !(lib->scaled_font_get_user_data =		getDLLEntry(pLib, "cairo_scaled_font_get_user_data"))) return 0;
		if( !(lib->scaled_font_set_user_data =		getDLLEntry(pLib, "cairo_scaled_font_set_user_data"))) return 0;
		if( !(lib->scaled_font_extents =			getDLLEntry(pLib, "cairo_scaled_font_extents"))) return 0;
		if( !(lib->scaled_font_text_extents =		getDLLEntry(pLib, "cairo_scaled_font_text_extents"))) return 0;
		if( !(lib->scaled_font_glyph_extents =		getDLLEntry(pLib, "cairo_scaled_font_glyph_extents"))) return 0;
		if( !(lib->scaled_font_get_font_face =		getDLLEntry(pLib, "cairo_scaled_font_get_font_face"))) return 0;
		if( !(lib->scaled_font_get_font_matrix =	getDLLEntry(pLib, "cairo_scaled_font_get_font_matrix"))) return 0;
		if( !(lib->scaled_font_get_ctm =			getDLLEntry(pLib, "cairo_scaled_font_get_ctm"))) return 0;
		if( !(lib->scaled_font_get_font_options =	getDLLEntry(pLib, "cairo_scaled_font_get_font_options"))) return 0;
		if( !(lib->get_operator =					getDLLEntry(pLib, "cairo_get_operator"))) return 0;
		if( !(lib->get_source =						getDLLEntry(pLib, "cairo_get_source"))) return 0;
		if( !(lib->get_tolerance =					getDLLEntry(pLib, "cairo_get_tolerance"))) return 0;
		if( !(lib->get_antialias =					getDLLEntry(pLib, "cairo_get_antialias"))) return 0;
		if( !(lib->get_current_point =				getDLLEntry(pLib, "cairo_get_current_point"))) return 0;
		if( !(lib->get_fill_rule =					getDLLEntry(pLib, "cairo_get_fill_rule"))) return 0;
		if( !(lib->get_line_width =					getDLLEntry(pLib, "cairo_get_line_width"))) return 0;
		if( !(lib->get_line_cap =					getDLLEntry(pLib, "cairo_get_line_cap"))) return 0;
		if( !(lib->get_line_join =					getDLLEntry(pLib, "cairo_get_line_join"))) return 0;
		if( !(lib->get_miter_limit =				getDLLEntry(pLib, "cairo_get_miter_limit"))) return 0;
		if( !(lib->get_dash_count =					getDLLEntry(pLib, "cairo_get_dash_count"))) return 0;
		if( !(lib->get_dash =						getDLLEntry(pLib, "cairo_get_dash"))) return 0;
		if( !(lib->get_matrix =						getDLLEntry(pLib, "cairo_get_matrix"))) return 0;
		if( !(lib->get_target =						getDLLEntry(pLib, "cairo_get_target"))) return 0;
		if( !(lib->get_group_target =				getDLLEntry(pLib, "cairo_get_group_target"))) return 0;
		if( !(lib->copy_path =						getDLLEntry(pLib, "cairo_copy_path"))) return 0;
		if( !(lib->copy_path_flat =					getDLLEntry(pLib, "cairo_copy_path_flat"))) return 0;
		if( !(lib->append_path =					getDLLEntry(pLib, "cairo_append_path"))) return 0;
		if( !(lib->path_destroy =					getDLLEntry(pLib, "cairo_path_destroy"))) return 0;
		if( !(lib->status =							getDLLEntry(pLib, "cairo_status"))) return 0;
		if( !(lib->status_to_string =				getDLLEntry(pLib, "cairo_status_to_string"))) return 0;
		if( !(lib->surface_create_similar =			getDLLEntry(pLib, "cairo_surface_create_similar"))) return 0;
		if( !(lib->surface_reference =				getDLLEntry(pLib, "cairo_surface_reference"))) return 0;
		if( !(lib->surface_finish =					getDLLEntry(pLib, "cairo_surface_finish"))) return 0;
		if( !(lib->surface_destroy =				getDLLEntry(pLib, "cairo_surface_destroy"))) return 0;
		if( !(lib->surface_get_reference_count =	getDLLEntry(pLib, "cairo_surface_get_reference_count"))) return 0;
		if( !(lib->surface_status =					getDLLEntry(pLib, "cairo_surface_status"))) return 0;
		if( !(lib->surface_get_type =				getDLLEntry(pLib, "cairo_surface_get_type"))) return 0;
		if( !(lib->surface_get_content =			getDLLEntry(pLib, "cairo_surface_get_content"))) return 0;
		if( !(lib->surface_get_user_data =			getDLLEntry(pLib, "cairo_surface_get_user_data"))) return 0;
		if( !(lib->surface_set_user_data =			getDLLEntry(pLib, "cairo_surface_set_user_data"))) return 0;
		if( !(lib->surface_get_font_options =		getDLLEntry(pLib, "cairo_surface_get_font_options"))) return 0;
		if( !(lib->surface_flush =					getDLLEntry(pLib, "cairo_surface_flush"))) return 0;
		if( !(lib->surface_mark_dirty =				getDLLEntry(pLib, "cairo_surface_mark_dirty"))) return 0;
		if( !(lib->surface_mark_dirty_rectangle =	getDLLEntry(pLib, "cairo_surface_mark_dirty_rectangle"))) return 0;
		if( !(lib->surface_set_device_offset =		getDLLEntry(pLib, "cairo_surface_set_device_offset"))) return 0;
		if( !(lib->surface_get_device_offset =		getDLLEntry(pLib, "cairo_surface_get_device_offset"))) return 0;
		if( !(lib->surface_set_fallback_resolution =getDLLEntry(pLib, "cairo_surface_set_fallback_resolution"))) return 0;
		if( !(lib->image_surface_create =			getDLLEntry(pLib, "cairo_image_surface_create"))) return 0;
		if( !(lib->image_surface_get_data =			getDLLEntry(pLib, "cairo_image_surface_get_data"))) return 0;
		if( !(lib->image_surface_get_format =		getDLLEntry(pLib, "cairo_image_surface_get_format"))) return 0;
		if( !(lib->image_surface_get_width =		getDLLEntry(pLib, "cairo_image_surface_get_width"))) return 0;
		if( !(lib->image_surface_get_height =		getDLLEntry(pLib, "cairo_image_surface_get_height"))) return 0;
		if( !(lib->image_surface_get_stride =		getDLLEntry(pLib, "cairo_image_surface_get_stride"))) return 0;
		if( !(lib->pattern_create_rgb	=			getDLLEntry(pLib, "cairo_pattern_create_rgb"))) return 0;
		if( !(lib->pattern_create_rgba =			getDLLEntry(pLib, "cairo_pattern_create_rgba"))) return 0;
		if( !(lib->pattern_create_for_surface =		getDLLEntry(pLib, "cairo_pattern_create_for_surface"))) return 0;
		if( !(lib->pattern_create_linear =			getDLLEntry(pLib, "cairo_pattern_create_linear"))) return 0;
		if( !(lib->pattern_create_radial =			getDLLEntry(pLib, "cairo_pattern_create_radial"))) return 0;
		if( !(lib->pattern_reference =				getDLLEntry(pLib, "cairo_pattern_reference"))) return 0;
		if( !(lib->pattern_destroy =				getDLLEntry(pLib, "cairo_pattern_destroy"))) return 0;
		if( !(lib->pattern_get_reference_count =	getDLLEntry(pLib, "cairo_pattern_get_reference_count"))) return 0;
		if( !(lib->pattern_status =					getDLLEntry(pLib, "cairo_pattern_status"))) return 0;
		if( !(lib->pattern_get_user_data =			getDLLEntry(pLib, "cairo_pattern_get_user_data"))) return 0;
		if( !(lib->pattern_set_user_data =			getDLLEntry(pLib, "cairo_pattern_set_user_data"))) return 0;
		if( !(lib->pattern_get_type =				getDLLEntry(pLib, "cairo_pattern_get_type"))) return 0;
		if( !(lib->pattern_add_color_stop_rgb =		getDLLEntry(pLib, "cairo_pattern_add_color_stop_rgb"))) return 0;
		if( !(lib->pattern_add_color_stop_rgba =	getDLLEntry(pLib, "cairo_pattern_add_color_stop_rgba"))) return 0;
		if( !(lib->pattern_set_matrix =				getDLLEntry(pLib, "cairo_pattern_set_matrix"))) return 0;
		if( !(lib->pattern_get_matrix =				getDLLEntry(pLib, "cairo_pattern_get_matrix"))) return 0;
		if( !(lib->pattern_set_extend =				getDLLEntry(pLib, "cairo_pattern_set_extend"))) return 0;
		if( !(lib->pattern_get_extend =				getDLLEntry(pLib, "cairo_pattern_get_extend"))) return 0;
		if( !(lib->pattern_set_filter =				getDLLEntry(pLib, "cairo_pattern_set_filter"))) return 0;
		if( !(lib->pattern_get_filter =				getDLLEntry(pLib, "cairo_pattern_get_filter"))) return 0;
		if( !(lib->pattern_get_rgba =				getDLLEntry(pLib, "cairo_pattern_get_rgba"))) return 0;
		if( !(lib->pattern_get_surface =			getDLLEntry(pLib, "cairo_pattern_get_surface"))) return 0;
		if( !(lib->pattern_get_color_stop_rgba =	getDLLEntry(pLib, "cairo_pattern_get_color_stop_rgba"))) return 0;
		if( !(lib->pattern_get_color_stop_count =	getDLLEntry(pLib, "cairo_pattern_get_color_stop_count"))) return 0;
		if( !(lib->pattern_get_linear_points =		getDLLEntry(pLib, "cairo_pattern_get_linear_points"))) return 0;
		if( !(lib->pattern_get_radial_circles =		getDLLEntry(pLib, "cairo_pattern_get_radial_circles"))) return 0;
		if( !(lib->matrix_init =					getDLLEntry(pLib, "cairo_matrix_init"))) return 0;
		if( !(lib->matrix_init_identity =			getDLLEntry(pLib, "cairo_matrix_init_identity"))) return 0;
		if( !(lib->matrix_init_translate =			getDLLEntry(pLib, "cairo_matrix_init_translate"))) return 0;
		if( !(lib->matrix_init_scale =				getDLLEntry(pLib, "cairo_matrix_init_scale"))) return 0;
		if( !(lib->matrix_init_rotate =				getDLLEntry(pLib, "cairo_matrix_init_rotate"))) return 0;
		if( !(lib->matrix_translate =				getDLLEntry(pLib, "cairo_matrix_translate"))) return 0;
		if( !(lib->matrix_scale =					getDLLEntry(pLib, "cairo_matrix_scale"))) return 0;
		if( !(lib->matrix_rotate =					getDLLEntry(pLib, "cairo_matrix_rotate"))) return 0;
		if( !(lib->matrix_invert =					getDLLEntry(pLib, "cairo_matrix_invert"))) return 0;
		if( !(lib->matrix_multiply =				getDLLEntry(pLib, "cairo_matrix_multiply"))) return 0;
		if( !(lib->matrix_transform_distance =		getDLLEntry(pLib, "cairo_matrix_transform_distance"))) return 0;
		if( !(lib->matrix_transform_point =			getDLLEntry(pLib, "cairo_matrix_transform_point"))) return 0;
		if( !(lib->debug_reset_static_data =		getDLLEntry(pLib, "cairo_debug_reset_static_data"))) return 0;
		if( !(lib->set_line_width =					getDLLEntry(pLib, "cairo_set_line_width"))) return 0;
		if( !(lib->surface_write_to_png =			getDLLEntry(pLib, "cairo_surface_write_to_png"))) return 0;
		if( !(lib->surface_write_to_png_stream =	getDLLEntry(pLib, "cairo_surface_write_to_png_stream"))) return 0;
		if( !(lib->image_surface_create_from_png =	getDLLEntry(pLib, "cairo_image_surface_create_from_png"))) return 0;
		if( !(lib->image_surface_create_from_png_stream = getDLLEntry(pLib, "cairo_image_surface_create_from_png_stream"))) return 0;
		
		return 1;
	}
	return 0;
}
#endif

#endif		